### ISSUE TITLE
Recent transactions do not appear at the bottom

### ISSUE THREAD

**Issue by adam6896** [anonanonymous/Shellnet#14]
Recent transactions do not appear at the bottom.

The rest of the wallet functions go well.
The version of the daemon it uses is 0.12.0.

**Comment by m4hdi1995** [comment]
@adam6896 it's not a completed work, it's an excellent wallet , hope @anonanonymous get it's done :)

**Comment by anonanonymous** [comment]
This issue was fixed in a recent commit.
Pull from master and it should work as intended :D

**Comment by adam6896** [comment]
Well, incoming transactions already appear. That is progress. 
But the exit transactions still do not appear. This same problem is also in the shellnet.pw
